version: '2.1'
services:
  nginx:
    build: docker/nginx
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/logs/:/var/log/nginx
      - /core:/var/www/core
  php:
    build: docker/php
    restart: always
    volumes:
      - /core:/var/www/core
  composer:
    image: composer:1.7.2
    volumes:
      - "/core:/app"
    command: install
